export const maxDuration = 30;

export default async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*")
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS")
  res.setHeader("Access-Control-Allow-Headers", "Content-Type")

  if (req.method === "OPTIONS") return res.status(200).end()
  if (req.method !== "POST") return res.status(405).end()

  const { email, todoList, itineraryTitle, chosenItineraryHTML } = req.body

  if (!email || !todoList) {
    return res.status(400).json({ error: "Missing email or todoList" })
  }

  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${process.env.RESEND_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from: process.env.FROM_EMAIL,
      to: email,
      subject: `Your Away Edit Itinerary — ${itineraryTitle || "Your Perfect Trip"}`,
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
        </head>
        <body style="margin:0;padding:0;background-color:#FAF8F5;font-family:Georgia,serif;">
          <div style="max-width:600px;margin:0 auto;padding:48px 24px;">
            <div style="border-bottom:1px solid rgb(38,78,51);padding-bottom:24px;margin-bottom:40px;">
              <p style="font-family:sans-serif;font-size:11px;letter-spacing:0.2em;text-transform:uppercase;color:rgb(38,78,51);margin:0 0 8px 0;">Your Curated Itinerary</p>
              <h1 style="font-family:Georgia,serif;font-weight:300;font-size:36px;color:rgb(38,78,51);margin:0;">The Away Edit</h1>
            </div>
            <p style="font-family:sans-serif;font-size:11px;letter-spacing:0.2em;text-transform:uppercase;color:rgb(38,78,51);margin:0 0 20px 0;">Your Chosen Itinerary</p>
            <div style="background:rgb(249,247,239);border:1px solid rgb(38,78,51);padding:32px;margin-bottom:40px;">
              ${chosenItineraryHTML || ""}
            </div>
            <p style="font-family:sans-serif;font-size:11px;letter-spacing:0.2em;text-transform:uppercase;color:rgb(38,78,51);margin:0 0 20px 0;">Your Planning Checklist</p>
            <div style="background:rgb(249,247,239);border:1px solid rgb(38,78,51);padding:32px;margin-bottom:40px;">
              ${todoList}
            </div>
            <div style="border-top:1px solid rgb(38,78,51);padding-top:24px;margin-top:40px;">
              <p style="font-family:sans-serif;font-size:12px;color:rgba(38,78,51,0.5);margin:0;">Generated by The Away Edit · theawayeditco.com · Please verify all bookings before confirming.</p>
            </div>
          </div>
        </body>
        </html>
      `,
    }),
  })

  const data = await response.json()

  if (!response.ok) {
    return res.status(500).json({ error: data.message || "Failed to send email" })
  }

  res.status(200).json({ success: true })
}
